language: python
python:
    - 3.6
before_install:
    - openssl aes-256-cbc -K $encrypted_990b012bc5a2_key -iv $encrypted_990b012bc5a2_iv -in .env.enc -out .env -d
addons:
    # https://docs.travis-ci.com/user/chrome
    # stable or beta
    chrome: stable
install:
    # ------------------
    # check chrome
    # ------------------
    - whereis google-chrome-stable
    - google-chrome-stable --version
    # ------------------
    # install chromedriver
    # ------------------
    - wget -N https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    - whereis chromedriver
    # ------------------
    # python module
    # ------------------
    - pip install pipenv
    - pipenv install --dev
    - pip install -e .
before_script:
    - flake8 --max-line-length=100 --ignore=E203,W503 ./mmlibrary
script:
    - py.test -v --capture=no --cov-config .coveragerc --cov=mmlibrary .
    - bash <(curl -s https://codecov.io/bash)
notifications:
    slack:
        secure: BhN8SJIStzxo00c/Eu019M4TMF0skzQqBtKDeMREoDTn/Sfo1eJNY52Sdg2vGbEygua/az/a9OOfEuDEuU367SFpwQq7BF4pE0w/5Zxkf/WKTisRUk3zvzulylsNF5RM6sYJw8SDbJyzr/Gv8elSlUX/yUpm4/BKnkI88p/wzKywSiTyXnRi29bpsnGSGy8c+KrPJYKnClts2HoDKApCfdKtwkBLW3IHn9Re/E0WQQUuYNUdhgqCYiRFegCXlMsJ1gEwAZuAurnioruDENKqmqrP3ceTgYs1kPZEwzZFuE8A3pHWf2ZJE2T1dUcxSV0Q2fpn31Y+mps2cDX4VZO4IGp8rddUW3QKFwYwMmmg6fPkmL/MqirfkxzXKN56IrXgYm8wWwPW7H1O2UV9Cyp4zgQVHIctLCQ87nrwkTaWAtXBbVjXti29HOf6orhYbqZAxyxmD7tIdokj2k0qGbiV0Asxe52UT3kFaCepUZllpa3roxWBFypIunNQ5kJyHeUszW+4oIp7LCZpT/KSMcyh8S/P6WuF4eIWeBQGkyBbJ2YXo7xbeJSw7GboaFtaKcaz4oI927Mn4+F65KN4wRnQnplbojJOPI7aK5Vfy+wht07vPiA3jWTF+alGOktQhFzb5f/B0DnG/g6L7zIlBcxfuOYGqTyeutPA7MPw7oKdVTs=
